library(caTools)
library(DMwR)
library(e1071)
rdata <- read.csv("/Users/deepak/Documents/fervez/creditcard.csv")
set.seed(1234)
rdata$Class<-factor(rdata$Class, levels=c(0,1))
split<-sample.split(rdata$Class, SplitRatio=0.7)
traindata<-subset(rdata, split=TRUE)
testdata<-subset(rdata, split=FALSE)
traindata$Class<-as.factor(traindata$Class)
traindata<-SMOTE(Class~., traindata, perc.over=200, perc.under=100)
str(data)
model<-naiveBayes(Class~.,data=traindata)
predict_target<-predict(model, testdata, type="class")
xtab<-table(testdata$Class, predict_target, dnn=c("actual","predict"))
library(caret) 
confusionMatrix(xtab)